My portfolio pull request
supreeti/First-Portfolio pull request #1
Opened 2022-12-01 15:20 UTC by supreeti

This is my first mobile portfolio project.

2022-12-01 18:22 UTC, Lizdev-05 requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
<img src="https://media1.giphy.com/media/5n1XqQh0DskgKMKejY/giphy.gif"/>
## Highlights
- Correct GitHub Flow 👍
- Good commit history 💰
- All linters passed 🏅
- Personalised README file 👍

## Required Changes ♻️

- [ ] Kindly stick to the design as much as possible (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).🙏

- [ ] Kindly make the style of your portfolio to be in accordance with [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=bW1SAmDOEVbj8Xk1-0) design provided by Microverse. 👇

| Your Design | Figma Design |
| :---:   | :---: | 
| <img width="376" alt="image" src="https://user-images.githubusercontent.com/73854999/205128900-57ecccda-8c5a-4f18-ae49-44bd342a833b.png">| <img width="376" alt="image" src="https://user-images.githubusercontent.com/73854999/205129264-029cfe71-106a-4b01-9489-02ad6c75ec1a.png">|

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 18:22 UTC, Lizdev-05 commented on index.html
> +            <img src="images/My Logo.png" alt=""/></a></div>
Great job adding a logo to your portfolio 👍. I think it will be better if you wrap your portfolio in an `a` tag so that users can navigate back to your home page from any other pages they may be. ⚔️😎

2022-12-02 06:15 UTC, binhussen approved these changes
Hi @supreeti, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions
- [Optional] Good job 👍, kindly follow the Figma design restrictly. 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 06:15 UTC, binhussen commented on index.html
> +        <h3 class="logo"><a href="#">My Logo</a></h3>
- [Optional] Kindly, follow the Figma design strictly including (font and color) 👌

![Screenshot 2022-12-02 090829](https://user-images.githubusercontent.com/52010789/205227038-aa639f34-266b-49ff-8fce-aafb26f7e52b.png)
your design logo does not match the Figma design 👆👆
![Screenshot 2022-12-02 090811](https://user-images.githubusercontent.com/52010789/205227044-4bbbb5cb-e0fa-4441-8f20-addf54863599.png)
the Figma design

2022-12-02 07:05 UTC, merged